### ISSUE TITLE
Not load on latest nukkit build  git-3da731d

### ISSUE THREAD

**Issue by twixi** [Leonidius20/TradingInterface#17]
`2024-08-06 10:40:54.388 [main] INFO  - Ввімкнення  Trading_Interface v2.0.0
2024-08-06 10:40:54.541 [main] ERROR - Throwing
java.lang.RuntimeException: java.lang.NoSuchMethodError: 'void org.sqlite.SQLiteConnection.setLimit(org.sqlite.SQLiteLimits, int)'
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:440) [nukkit.jar:?]
	at cn.nukkit.Server.enablePlugin(Server.java:755) [nukkit.jar:?]
	at cn.nukkit.Server.enablePlugins(Server.java:744) [nukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:587) [nukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:120) [nukkit.jar:?]
Caused by: java.lang.NoSuchMethodError: 'void org.sqlite.SQLiteConnection.setLimit(org.sqlite.SQLiteLimits, int)'
	at org.sqlite.SQLiteConfig.apply(SQLiteConfig.java:127) ~[?:?]
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65) ~[?:?]
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28) ~[?:?]
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21) ~[?:?]
	at org.sqlite.JDBC.createConnection(JDBC.java:116) ~[?:?]
	at org.sqlite.JDBC.connect(JDBC.java:90) ~[?:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:683) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:191) ~[java.sql:?]
	at com.j256.ormlite.jdbc.JdbcConnectionSource.makeConnection(JdbcConnectionSource.java:266) ~[?:?]
	at ru.nukkit.dblib.connectionsource.LockedJdbcSingleConnectionSource.initialize(LockedJdbcSingleConnectionSource.java:42) ~[?:?]
	at com.j256.ormlite.jdbc.JdbcConnectionSource.<init>(JdbcConnectionSource.java:117) ~[?:?]
	at ru.nukkit.dblib.connectionsource.LockedJdbcSingleConnectionSource.<init>(LockedJdbcSingleConnectionSource.java:36) ~[?:?]
	at ru.nukkit.dblib.DbLib.getConnectionSource(DbLib.java:74) ~[?:?]
	at ua.leonidius.trdinterface.Trading.onEnable(Trading.java:55) ~[?:?]
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[nukkit.jar:?]
	... 4 more
2024-08-06 10:40:54.552 [main] INFO  - Вимкнення Trading_Interface v2.0.0
2024-08-06 10:40:54.552 [main] ERROR - Throwing
java.lang.NullPointerException: Cannot invoke "com.j256.ormlite.support.ConnectionSource.closeQuietly()" because "ua.leonidius.trdinterface.Trading.source" is null
	at ua.leonidius.trdinterface.Trading.onDisable(Trading.java:107) ~[?:?]
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:91) ~[nukkit.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:132) ~[nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:510) [nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:442) [nukkit.jar:?]
	at cn.nukkit.Server.enablePlugin(Server.java:755) [nukkit.jar:?]
	at cn.nukkit.Server.enablePlugins(Server.java:744) [nukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:587) [nukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:120) [nukkit.jar:?]
`

**Comment by twixi** [comment]
`[ERROR] Throwing
java.lang.RuntimeException: java.lang.NoSuchMethodError: 'void org.sqlite.SQLite                                                                                                                                   Connection.setLimit(org.sqlite.SQLiteLimits, int)'
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:440) [                                                                                                                                   nukkit_1117.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:755) [nukkit_1117.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:744) [nukkit_1117.jar:?]
        at cn.nukkit.Server.<init>(Server.java:587) [nukkit_1117.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [nukkit_1117.jar:?]
Caused by: java.lang.NoSuchMethodError: 'void org.sqlite.SQLiteConnection.setLim                                                                                                                                   it(org.sqlite.SQLiteLimits, int)'
        at org.sqlite.SQLiteConfig.apply(SQLiteConfig.java:127) ~[?:?]
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65) ~[?:?]
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28) ~[?:                                                                                                                                   ?]
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21) ~[?:                                                                                                                                   ?]
        at org.sqlite.JDBC.createConnection(JDBC.java:116) ~[?:?]
        at org.sqlite.JDBC.connect(JDBC.java:90) ~[?:?]
        at java.sql.DriverManager.getConnection(DriverManager.java:683) ~[java.s                                                                                                                                   ql:?]
        at java.sql.DriverManager.getConnection(DriverManager.java:191) ~[java.s                                                                                                                                   ql:?]
        at com.j256.ormlite.jdbc.JdbcConnectionSource.makeConnection(JdbcConnect                                                                                                                                   ionSource.java:266) ~[?:?]
        at ru.nukkit.dblib.connectionsource.LockedJdbcSingleConnectionSource.ini                                                                                                                                   tialize(LockedJdbcSingleConnectionSource.java:42) ~[?:?]
        at com.j256.ormlite.jdbc.JdbcConnectionSource.<init>(JdbcConnectionSourc                                                                                                                                   e.java:117) ~[?:?]
        at ru.nukkit.dblib.connectionsource.LockedJdbcSingleConnectionSource.<in                                                                                                                                   it>(LockedJdbcSingleConnectionSource.java:36) ~[?:?]
        at ru.nukkit.dblib.DbLib.getConnectionSource(DbLib.java:74) ~[?:?]
        at ua.leonidius.trdinterface.Trading.onEnable(Trading.java:55) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit_1                                                                                                                                   117.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:                                                                                                                                   117) ~[nukkit_1117.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~                                                                                                                                   [nukkit_1117.jar:?]
        ... 4 more
`
